---
name: Pre-build osxcross
on:
  workflow_dispatch:
    inputs:
      version:
        description: macOS Version for SDK
        required: true
        type: string
        default: "10.13"
jobs:
  build-linux-x86-64:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: build and archive
        run: |
          wget -P tarballs https://github.com/joseluisq/macosx-sdks/releases/download/${{ inputs.version }}/MacOSX${{ inputs.version }}.sdk.tar.xz
          UNATTENDED=1 TARGET_DIR=${{ github.workspace }}/osxcross ./build.sh
          tar -cvf osxcross.tar osxcross
          xz -9 osxcross.tar
      - name: post artifacts
        uses: actions/upload-artifact@v6
        with:
          name: osxcross-linux-x86-64.tar.xz
          path: osxcross.tar.xz
